version: "3"

services:

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /home/yan/ProjetWetteren/mongo-backup:/data/db
    networks:
      - mern-network

  server-nginx:
    image: nginx:latest
    container_name: serv-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./servweb/dist:/var/www/html
      - ./servweb/certificate:/etc/nginx/certificates
      - ./servweb/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge